CREATE TABLE addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street VARCHAR(255) NOT NULL,
    number VARCHAR(255) NOT NULL,
    complement VARCHAR(255),
    neighborhood VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    zip_code VARCHAR(255) NOT NULL,
    latitude NUMERIC(38, 8),
    longitude NUMERIC(38, 8)
);

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    date_of_birth DATE NOT NULL,
    registration_date TIMESTAMP NOT NULL,
    email_verified_at TIMESTAMP NOT NULL,
    role VARCHAR(32) NOT NULL,
    address_id BIGINT UNIQUE,
    CONSTRAINT fk_users_address FOREIGN KEY (address_id) REFERENCES addresses (id)
);

CREATE TABLE drivers (
    user_id BIGINT PRIMARY KEY,
    cnh VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL,
    status_reason VARCHAR(255),
    reviewed_at TIMESTAMP,
    CONSTRAINT fk_drivers_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE institutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    institution_type VARCHAR(32) NOT NULL,
    address_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_institutions_address FOREIGN KEY (address_id) REFERENCES addresses (id)
);

CREATE TABLE students (
    user_id BIGINT PRIMARY KEY,
    institution_id BIGINT,
    CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_students_institution FOREIGN KEY (institution_id) REFERENCES institutions (id)
);

CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    manufacturing_year INTEGER,
    license_plate VARCHAR(255) NOT NULL UNIQUE,
    passenger_capacity INTEGER NOT NULL,
    color VARCHAR(255),
    driver_id BIGINT NOT NULL,
    CONSTRAINT fk_vehicles_driver FOREIGN KEY (driver_id) REFERENCES drivers (user_id)
);

CREATE TABLE driver_invite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    expired_at TIMESTAMP,
    CONSTRAINT fk_driver_invite_driver FOREIGN KEY (driver_id) REFERENCES drivers (user_id)
);

CREATE TABLE driver_student_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT fk_links_driver FOREIGN KEY (driver_id) REFERENCES drivers (user_id),
    CONSTRAINT fk_links_student FOREIGN KEY (student_id) REFERENCES students (user_id)
);

CREATE TABLE student_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    day_of_week VARCHAR(16) NOT NULL,
    time TIME NOT NULL,
    direction VARCHAR(16) NOT NULL,
    CONSTRAINT fk_schedules_student FOREIGN KEY (student_id) REFERENCES students (user_id),
    CONSTRAINT uk_student_schedule UNIQUE (student_id, day_of_week, time, direction)
);

CREATE TABLE email_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    code_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    attempt_count INTEGER NOT NULL,
    last_sent_at TIMESTAMP NOT NULL,
    verified_at TIMESTAMP,
    registration_token_hash VARCHAR(255) UNIQUE,
    registration_token_expires_at TIMESTAMP,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    invalidated_at TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE INDEX idx_driver_status ON drivers (status);
CREATE INDEX idx_invite_driver_status ON driver_invite (driver_id, status);
CREATE INDEX idx_links_driver_status ON driver_student_links (driver_id, status);
CREATE INDEX idx_links_student_status ON driver_student_links (student_id, status);
CREATE INDEX idx_schedules_student ON student_schedules (student_id);
CREATE INDEX idx_refresh_user_status ON refresh_tokens (user_id, status);
