ALTER TABLE drivers ADD COLUMN operational_address_id BIGINT;
ALTER TABLE drivers ADD CONSTRAINT fk_drivers_operational_address
    FOREIGN KEY (operational_address_id) REFERENCES addresses (id);

ALTER TABLE vehicles ADD COLUMN default_vehicle BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE daily_confirmations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    driver_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    service_date DATE NOT NULL,
    direction VARCHAR(16) NOT NULL,
    scheduled_time TIME NOT NULL,
    preliminary_departure_at TIMESTAMP NOT NULL,
    available_at TIMESTAMP NOT NULL,
    response_deadline TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL,
    responded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_confirmations_driver FOREIGN KEY (driver_id) REFERENCES drivers (user_id),
    CONSTRAINT fk_confirmations_student FOREIGN KEY (student_id) REFERENCES students (user_id),
    CONSTRAINT uk_daily_confirmation UNIQUE (student_id, service_date, direction)
);

CREATE TABLE trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    driver_id BIGINT NOT NULL,
    vehicle_id BIGINT,
    service_date DATE NOT NULL,
    direction VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    planned_departure_at TIMESTAMP,
    driver_departure_at TIMESTAMP,
    departure_confirmed_at TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    cancellation_reason VARCHAR(500),
    planning_issue VARCHAR(1000),
    route_provider VARCHAR(32),
    route_reference VARCHAR(255),
    encoded_polyline TEXT,
    route_calculated_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_trips_driver FOREIGN KEY (driver_id) REFERENCES drivers (user_id),
    CONSTRAINT fk_trips_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
);

CREATE TABLE trip_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    confirmation_id BIGINT NOT NULL UNIQUE,
    pickup_order INTEGER NOT NULL,
    dropoff_order INTEGER NOT NULL,
    estimated_pickup_at TIMESTAMP,
    estimated_dropoff_at TIMESTAMP,
    CONSTRAINT fk_participants_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_participants_student FOREIGN KEY (student_id) REFERENCES students (user_id),
    CONSTRAINT fk_participants_confirmation FOREIGN KEY (confirmation_id) REFERENCES daily_confirmations (id),
    CONSTRAINT uk_trip_student UNIQUE (trip_id, student_id)
);

CREATE TABLE in_app_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    type VARCHAR(64) NOT NULL,
    title VARCHAR(120) NOT NULL,
    message VARCHAR(500) NOT NULL,
    trip_id BIGINT,
    confirmation_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP,
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users (user_id),
    CONSTRAINT fk_notifications_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_notifications_confirmation FOREIGN KEY (confirmation_id) REFERENCES daily_confirmations (id)
);

CREATE INDEX idx_confirmations_student_date ON daily_confirmations (student_id, service_date);
CREATE INDEX idx_confirmations_driver_date ON daily_confirmations (driver_id, service_date);
CREATE INDEX idx_confirmations_status_deadline ON daily_confirmations (status, response_deadline);
CREATE INDEX idx_trips_driver_date ON trips (driver_id, service_date);
CREATE INDEX idx_trips_status_departure ON trips (status, planned_departure_at);
CREATE INDEX idx_participants_trip ON trip_participants (trip_id);
CREATE INDEX idx_notifications_recipient_created ON in_app_notifications (recipient_id, created_at);
CREATE INDEX idx_notifications_recipient_read ON in_app_notifications (recipient_id, read_at);
