CREATE TABLE recurring_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT NOT NULL,
    vehicle_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_recurring_routes_driver FOREIGN KEY (driver_id) REFERENCES drivers (user_id),
    CONSTRAINT fk_recurring_routes_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
);

CREATE TABLE recurring_route_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL,
    day_of_week VARCHAR(16) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    departure_time TIME NOT NULL,
    response_deadline_time TIME NOT NULL,
    CONSTRAINT fk_recurring_route_schedules_route FOREIGN KEY (route_id) REFERENCES recurring_routes (id),
    CONSTRAINT uk_recurring_route_schedule UNIQUE (route_id, day_of_week, direction)
);

CREATE TABLE recurring_route_institutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL,
    institution_id BIGINT NOT NULL,
    stop_order INTEGER NOT NULL,
    outbound_arrival_by TIME,
    return_departure_at TIME,
    CONSTRAINT fk_recurring_route_institutions_route FOREIGN KEY (route_id) REFERENCES recurring_routes (id),
    CONSTRAINT fk_recurring_route_institutions_institution FOREIGN KEY (institution_id) REFERENCES institutions (id),
    CONSTRAINT uk_recurring_route_institution UNIQUE (route_id, institution_id)
);

CREATE TABLE recurring_route_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    outbound_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    return_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(16) NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    reviewed_at TIMESTAMP,
    CONSTRAINT fk_recurring_route_enrollments_route FOREIGN KEY (route_id) REFERENCES recurring_routes (id),
    CONSTRAINT fk_recurring_route_enrollments_student FOREIGN KEY (student_id) REFERENCES students (user_id),
    CONSTRAINT uk_recurring_route_enrollment UNIQUE (route_id, student_id)
);

CREATE INDEX idx_recurring_routes_driver_active ON recurring_routes (driver_id, active);
CREATE INDEX idx_recurring_route_enrollments_student ON recurring_route_enrollments (student_id, status);
