import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { createInstitution, deleteInstitution, institutions, updateInstitution, type Institution, type InstitutionPayload } from './api'
import { PostalCodeInput } from '../../components/PostalCodeInput'
import { AddressMap } from '../location/AddressMap'

const empty = { name: '', type: 'UNIVERSITY', street: '', number: '', complement: '', neighborhood: '', city: '', state: '', zipCode: '', latitude: null as number | null, longitude: null as number | null }

export function InstitutionsPage() {
  const client = useQueryClient()
  const list = useQuery({ queryKey: ['institutions'], queryFn: institutions })
  const [form, setForm] = useState(empty)
  const [editing, setEditing] = useState<Institution | null>(null)
  const save = useMutation({ mutationFn: (payload: InstitutionPayload) => editing ? updateInstitution(editing.id, payload) : createInstitution(payload), onSuccess: async () => { setForm(empty); setEditing(null); await client.invalidateQueries({ queryKey: ['institutions'] }) } })
  const remove = useMutation({ mutationFn: deleteInstitution, onSuccess: () => void client.invalidateQueries({ queryKey: ['institutions'] }) })
  function submit(event: FormEvent) { event.preventDefault(); save.mutate({ name: form.name, type: form.type, address: { street: form.street, number: form.number, complement: form.complement || null, neighborhood: form.neighborhood, city: form.city, state: form.state.toUpperCase(), zipCode: form.zipCode, latitude: form.latitude, longitude: form.longitude } }) }
  function edit(item: Institution) { setEditing(item); setForm({ name: item.name, type: item.type, street: item.address.street, number: item.address.number, complement: item.address.complement ?? '', neighborhood: item.address.neighborhood, city: item.address.city, state: item.address.state, zipCode: item.address.zipCode, latitude: item.address.latitude, longitude: item.address.longitude }) }
  function cancel() { setEditing(null); setForm(empty); save.reset() }
  return <div className="page-stack"><header className="page-heading"><p className="eyebrow">Administração</p><h1>Instituições</h1><p className="muted">Cadastre e corrija os destinos disponíveis para os alunos.</p></header>{[list.error, save.error, remove.error].filter(Boolean).map((error, index) => <p role="alert" className="form-error" key={index}>{error?.message}</p>)}<div className="card-list">{list.data?.map((item) => <article className="trip-card" key={item.id}><div><strong>{item.name}</strong><p className="muted">{item.address.street}, {item.address.number} · {item.address.neighborhood}, {item.address.city}/{item.address.state} · CEP {item.address.zipCode}</p></div><div className="button-row"><span className="tag neutral">{item.type}</span><button className="secondary-button" onClick={() => edit(item)}>Editar</button><button className="text-button" disabled={remove.isPending} onClick={() => { if (window.confirm(`Excluir ${item.name}?`)) remove.mutate(item.id) }}>Excluir</button></div></article>)}</div><form className="inline-form institution-form" onSubmit={submit}><h3>{editing ? 'Editar instituição' : 'Nova instituição'}</h3><input aria-label="Nome" placeholder="Nome" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /><select aria-label="Tipo" value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="UNIVERSITY">Universidade</option><option value="SCHOOL">Escola</option><option value="TECHNICAL_SCHOOL">Escola técnica</option><option value="COURSE">Curso</option><option value="OTHER">Outra</option></select>{(['street', 'number', 'complement', 'neighborhood', 'city', 'state'] as const).map((field) => <input aria-label={labels[field]} key={field} placeholder={labels[field]} maxLength={field === 'state' ? 2 : undefined} value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value, ...(field === 'complement' ? {} : { latitude: null, longitude: null }) })} required={field !== 'complement'} />)}<PostalCodeInput value={form.zipCode} onChange={zipCode => setForm({ ...form, zipCode, latitude: null, longitude: null })} onResolved={address => setForm({ ...form, ...address, latitude: null, longitude: null })} /><AddressMap address={{ street: form.street, number: form.number, complement: form.complement || null, neighborhood: form.neighborhood, city: form.city, state: form.state, zipCode: form.zipCode }} latitude={form.latitude} longitude={form.longitude} onConfirm={(latitude, longitude) => setForm({ ...form, latitude, longitude })} /><div className="button-row"><button className="primary-button compact" disabled={save.isPending || form.latitude == null || form.longitude == null}>{editing ? 'Salvar alterações' : 'Cadastrar instituição'}</button>{editing && <button type="button" className="secondary-button" onClick={cancel}>Cancelar</button>}</div></form></div>
}

const labels = { street: 'Rua', number: 'Número', complement: 'Complemento', neighborhood: 'Bairro', city: 'Cidade', state: 'UF', zipCode: 'CEP' }
